/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#include <stdlib.h>
#include <time.h>

#include "main.h"
#include "interface.h"

#include "world.h"
#include "view.h"

CWorld *_world;

GtkWidget *window;

int main (int argc, char *argv[])
{  
  gtk_init (&argc, &argv);
  
  _world = new CWorld();
  srand(time(NULL));

  window = create_window ();
  gtk_widget_show (window);

  gtk_main ();
  return 0;
}
